# Visualization: Calculating with scales

In [1]:
] activate .

Activating environment at `C:\Users\carsten\.julia\dev\StableDQMC.jl\notebooks\scales_visualizations\Project.toml`


## Using `String` and `Char` (type piracy)

In [2]:
using Latexify

In [155]:
# const small, medium, large = 'ₓ', 'x', 'X'
const tiny, small, medium, large = 't','s', 'M', 'L'
# const small, medium, large = '🞄', '●', '⬤'
# const small, medium, large = '▪', '■', '⬛'

('t', 's', 'M', 'L')

In [157]:
const scale2value = Dict(tiny => 1, small => 2, medium => 3, large => 4)

Dict{Char,Int64} with 4 entries:
  'M' => 3
  'L' => 4
  's' => 2
  't' => 1

In [158]:
Base.zero(::Type{String}) = " "
Base.zero(::String) = zero(String)

Base.zero(::Type{Char}) = ' '
Base.zero(::Char) = zero(Char)

function Base.:+(x::String, y::String)
    if occursin(zero(String), x)
        if occursin(zero(String), y)
            return zero(String)
        else
            return y
        end
    elseif occursin(zero(String), y)
        return x
    else
       return sum(scale2value[c] for c in x) < sum(Int.(collect(y))) ? y : x #mean(x) < mean(y) ? y : x 
    end
end

function Base.:+(x::Char, y::Char)
    if x == zero(Char)
        if y == zero(Char)
            return zero(Char)
        else
            return y
        end
    elseif y == zero(Char)
        return x
    else
       return scale2value[x] > scale2value[y] ? x : y
    end
end

In [159]:
using LinearAlgebra
D = diagm(0 => [large, medium, small])

3×3 Array{Char,2}:
 'L'  ' '  ' '
 ' '  'M'  ' '
 ' '  ' '  's'

In [160]:
set_default(convert_unicode = false)

In [161]:
D |> latexify

L"\begin{equation}
\left[
\begin{array}{ccc}
L &   &   \\
  & M &   \\
  &   & s \\
\end{array}
\right]
\end{equation}
"

In [162]:
D * [large, medium, small] |> latexify

L"\begin{equation}
\left[
\begin{array}{c}
LL \\
MM \\
ss \\
\end{array}
\right]
\end{equation}
"

In [163]:
D * [small, small, small] |> latexify

L"\begin{equation}
\left[
\begin{array}{c}
Ls \\
Ms \\
ss \\
\end{array}
\right]
\end{equation}
"

In [164]:
O = zeros(Char, 3,3)
O |> latexify

L"\begin{equation}
\left[
\begin{array}{ccc}
  &   &   \\
  &   &   \\
  &   &   \\
\end{array}
\right]
\end{equation}
"

In [165]:
U = fill(small, 3,3)
U |> latexify

L"\begin{equation}
\left[
\begin{array}{ccc}
s & s & s \\
s & s & s \\
s & s & s \\
\end{array}
\right]
\end{equation}
"

In [166]:
U * D |> latexify

L"\begin{equation}
\left[
\begin{array}{ccc}
sL & sM & ss \\
sL & sM & ss \\
sL & sM & ss \\
\end{array}
\right]
\end{equation}
"

In [167]:
D * U * D |> latexify

L"\begin{equation}
\left[
\begin{array}{ccc}
LsL & LsM & Lss \\
MsL & MsM & Mss \\
ssL & ssM & sss \\
\end{array}
\right]
\end{equation}
"

In [168]:
print(ans)

\begin{equation}
\left[
\begin{array}{ccc}
LsL & LsM & Lss \\
MsL & MsM & Mss \\
ssL & ssM & sss \\
\end{array}
\right]
\end{equation}


In [169]:
U*D |> latexify

L"\begin{equation}
\left[
\begin{array}{ccc}
sL & sM & ss \\
sL & sM & ss \\
sL & sM & ss \\
\end{array}
\right]
\end{equation}
"

#### 4x4

In [171]:
using LinearAlgebra
D = diagm(0 => [large, medium, small, tiny])

4×4 Array{Char,2}:
 'L'  ' '  ' '  ' '
 ' '  'M'  ' '  ' '
 ' '  ' '  's'  ' '
 ' '  ' '  ' '  't'

In [174]:
U = fill(small, 4,4)
U |> latexify

L"\begin{equation}
\left[
\begin{array}{cccc}
s & s & s & s \\
s & s & s & s \\
s & s & s & s \\
s & s & s & s \\
\end{array}
\right]
\end{equation}
"

In [175]:
D*U*D |> latexify

L"\begin{equation}
\left[
\begin{array}{cccc}
LsL & LsM & Lss & Lst \\
MsL & MsM & Mss & Mst \\
ssL & ssM & sss & sst \\
tsL & tsM & tss & tst \\
\end{array}
\right]
\end{equation}
"

## Using Sympy

In [7]:
using SymPy

In [31]:
X, x, ₓ = @vars X x ₓ

(X, x, ₓ)

In [28]:
D = diagm([X,x,ₓ])

3×3 Array{Sym,2}:
 X  0  0
 0  x  0
 0  0  ₓ

In [29]:
U = fill(x, 3,3)

3×3 Array{Sym,2}:
 x  x  x
 x  x  x
 x  x  x

In [30]:
U*D

3×3 Array{Sym,2}:
 X*x  x^2  x*ₓ
 X*x  x^2  x*ₓ
 X*x  x^2  x*ₓ

In [ ]:
⚫, ⬤, ●, 🞄 = @vars ⚫ ⬤ ● 🞄

In [49]:
D = diagm([⚫, ⬤, ●, 🞄])

4×4 Array{Sym,2}:
 ⚫  0  0  0
 0  ⬤  0  0
 0  0  ●  0
 0  0  0  🞄

In [9]:
Diagonal([1000, 100, 10, 1]) |> latexify

L"\begin{equation}
\left[
\begin{array}{cccc}
1000 & 0 & 0 & 0 \\
0 & 100 & 0 & 0 \\
0 & 0 & 10 & 0 \\
0 & 0 & 0 & 1 \\
\end{array}
\right]
\end{equation}
"

In [15]:
⬛, ■, ◾, ▪ = @vars ⬛ ■ ◾ ▪

(⬛, ■, ◾, ▪)

In [16]:
d = [⬛, ■, ◾, ▪]

4-element Array{Sym,1}:
 ⬛
 ■
 ◾
 ▪

In [18]:
D = diagm(d)

4×4 Array{Sym,2}:
 ⬛  0  0  0
 0  ■  0  0
 0  0  ◾  0
 0  0  0  ▪

In [21]:
U = fill(◾, 4,4)

4×4 Array{Sym,2}:
 ◾  ◾  ◾  ◾
 ◾  ◾  ◾  ◾
 ◾  ◾  ◾  ◾
 ◾  ◾  ◾  ◾

In [28]:
R = D*U*D

4×4 Array{Sym,2}:
 ◾*⬛^2  ■*◾*⬛  ◾^2*⬛  ▪*◾*⬛
 ■*◾*⬛  ■^2*◾  ■*◾^2  ■*▪*◾
 ◾^2*⬛  ■*◾^2    ◾^3  ▪*◾^2
 ▪*◾*⬛  ■*▪*◾  ▪*◾^2  ▪^2*◾

## Using custom types

In [1]:
] activate .

Activating environment at `C:\Users\carsten\.julia\dev\StableDQMC.jl\notebooks\scales_visualizations\Project.toml`


In [92]:
@enum Scale null=1 tiny=2 small=3 medium=4 large=5
const unit=small
# const scale_symbols = [' ', '▪', '◾', '■', '⬛'];
const scale_symbols = [' ', 't', 's', 'M', 'L'];
# const scale_symbols = [' ', 'ₓ', 'u', 'x', 'X'];

symbol(s::Scale) = scale_symbols[Int(s)]
Base.isascii(::Scale) = false
Base.isoverlong(::Scale) = false
Base.ismalformed(::Scale) = false
Base.isprint(::Scale) = true

# printing
Base.show(io::IO, s::Scale) = print(io, symbol(s))
Base.show(io::IO, ::MIME"text/plain", s::Scale) = show(io,s)
Base.print(io::IO, s::Scale) = show(io, s)

# math
Base.zero(::Type{Scale}) = null
Base.iszero(s::Scale) = s === null

In [93]:
scales = null, tiny, small, medium, large

( , t, s, M, L)

In [94]:
using Statistics

struct ScaleString <: AbstractString
    scales::Vector{Scale}
end

# constructors
ScaleString(s::Scale) = ScaleString([s])

import Lazy: @forward
@forward ScaleString.scales (Base.getindex, Base.length)

# conversion
Base.convert(::Type{ScaleString}, s::Scale) = ScaleString(s)
Base.promote_rule(::Type{Scale}, ::Type{ScaleString}) = ScaleString

Base.iterate(s::ScaleString) = iterate(s.scales)
Base.iterate(s::ScaleString, state::Integer) = iterate(s.scales, state)

# Base.:+(x::ScaleString, y::ScaleString) = ScaleString(vcat(x.scales, null, null, y.scales))
Base.:*(x::ScaleString, y::ScaleString) = ScaleString(vcat(x.scales, y.scales))
Base.zero(::Type{ScaleString}) = ScaleString(zero(Scale))
Base.zero(::ScaleString) = zero(ScaleString)
function Base.:+(x::ScaleString, y::ScaleString)
    if null in x.scales
        if null in y.scales
            # both contain a null
            return ScaleString([null])
        else
            # only x contains a null
            return y
        end
    elseif null in y.scales
        # only y contains a null
        return x
    else
       return sum(Int.(x.scales)) < sum(Int.(y.scales)) ? y : x #mean(x) < mean(y) ? y : x 
    end
end
Base.:*(x::ScaleString, y::Scale) = iszero(y) ? ScaleString([null]) : ScaleString(vcat(x.scales, y))
Base.:*(x::Scale, y::ScaleString) = iszero(x) ? ScaleString([null]) : ScaleString(vcat(x, y.scales))

# Scale math extension
Base.:+(x::Scale, y::Scale) = x > y ? x : y
Base.:/(s::Scale, i::Int64) = /(Int(s), i)
function Base.:*(x::Scale, y::Scale)
#     if iszero(x)
#         return ScaleString([y])
#     elseif iszero(y)
#         return ScaleString([x])
#     else
        return ScaleString([x,y])
#     end
end

In [95]:
tiny * null

"t "

In [96]:
A = ScaleString([tiny, small, small])
B = ScaleString([null, large, small])

" Ls"

In [97]:
using Latexify

Latexify.latexraw(s::Scale) = symbol(s)
Latexify.latexraw(s::ScaleString) = join(s.scales)

In [98]:
O = zeros(Scale, 4,4)

4×4 Array{Scale,2}:
           
           
           
           

In [99]:
U = fill(unit, 4,4)

4×4 Array{Scale,2}:
 s  s  s  s
 s  s  s  s
 s  s  s  s
 s  s  s  s

In [100]:
U |> latexify

L"\begin{equation}
\left[
\begin{array}{cccc}
s & s & s & s \\
s & s & s & s \\
s & s & s & s \\
s & s & s & s \\
\end{array}
\right]
\end{equation}
"

In [101]:
U * U |> latexify

L"\begin{equation}
\left[
\begin{array}{cccc}
ss & ss & ss & ss \\
ss & ss & ss & ss \\
ss & ss & ss & ss \\
ss & ss & ss & ss \\
\end{array}
\right]
\end{equation}
"

In [102]:
U * O

4×4 Array{ScaleString,2}:
 " "  " "  " "  " "
 " "  " "  " "  " "
 " "  " "  " "  " "
 " "  " "  " "  " "

In [103]:
using LinearAlgebra
D = diagm([large, medium, small, tiny])

4×4 Array{Scale,2}:
 L         
    M      
       s   
          t

In [104]:
D |> latexify

L"\begin{equation}
\left[
\begin{array}{cccc}
L &   &   &   \\
  & M &   &   \\
  &   & s &   \\
  &   &   & t \\
\end{array}
\right]
\end{equation}
"

In [105]:
U * D |> latexify

L"\begin{equation}
\left[
\begin{array}{cccc}
sL & sM & ss & st \\
sL & sM & ss & st \\
sL & sM & ss & st \\
sL & sM & ss & st \\
\end{array}
\right]
\end{equation}
"

In [106]:
D * U * D |> latexify

L"\begin{equation}
\left[
\begin{array}{cccc}
LsL & LsM & Lss & Lst \\
MsL & MsM & Mss & Mst \\
ssL & ssM & sss & sst \\
tsL & tsM & tss & tst \\
\end{array}
\right]
\end{equation}
"

In [107]:
D * [small, small, small, small] |> latexify

L"\begin{equation}
\left[
\begin{array}{c}
Ls \\
Ms \\
ss \\
ts \\
\end{array}
\right]
\end{equation}
"

In [108]:
D * [large, medium, small, tiny] |> latexify

L"\begin{equation}
\left[
\begin{array}{c}
LL \\
MM \\
ss \\
tt \\
\end{array}
\right]
\end{equation}
"

In [109]:
R = D * U * D
R[1] == ScaleString([large,unit,large])

true