# Visualization: Calculating with scales

In [1]:
] activate .

Activating environment at `C:\Users\carsten\.julia\dev\StableDQMC.jl\notebooks\scales_visualizations\Project.toml`


## Using `String` and `Char` (type piracy)

In [2]:
using Latexify

In [155]:
# const small, medium, large = 'ₓ', 'x', 'X'
const tiny, small, medium, large = 't','s', 'M', 'L'
# const small, medium, large = '🞄', '●', '⬤'
# const small, medium, large = '▪', '■', '⬛'

('t', 's', 'M', 'L')

In [157]:
const scale2value = Dict(tiny => 1, small => 2, medium => 3, large => 4)

Dict{Char,Int64} with 4 entries:
  'M' => 3
  'L' => 4
  's' => 2
  't' => 1

In [158]:
Base.zero(::Type{String}) = " "
Base.zero(::String) = zero(String)

Base.zero(::Type{Char}) = ' '
Base.zero(::Char) = zero(Char)

function Base.:+(x::String, y::String)
    if occursin(zero(String), x)
        if occursin(zero(String), y)
            return zero(String)
        else
            return y
        end
    elseif occursin(zero(String), y)
        return x
    else
       return sum(scale2value[c] for c in x) < sum(Int.(collect(y))) ? y : x #mean(x) < mean(y) ? y : x 
    end
end

function Base.:+(x::Char, y::Char)
    if x == zero(Char)
        if y == zero(Char)
            return zero(Char)
        else
            return y
        end
    elseif y == zero(Char)
        return x
    else
       return scale2value[x] > scale2value[y] ? x : y
    end
end

In [159]:
using LinearAlgebra
D = diagm(0 => [large, medium, small])

3×3 Array{Char,2}:
 'L'  ' '  ' '
 ' '  'M'  ' '
 ' '  ' '  's'

In [160]:
set_default(convert_unicode = false)

In [161]:
D |> latexify

L"\begin{equation}
\left[
\begin{array}{ccc}
L &   &   \\
  & M &   \\
  &   & s \\
\end{array}
\right]
\end{equation}
"

In [162]:
D * [large, medium, small] |> latexify

L"\begin{equation}
\left[
\begin{array}{c}
LL \\
MM \\
ss \\
\end{array}
\right]
\end{equation}
"

In [163]:
D * [small, small, small] |> latexify

L"\begin{equation}
\left[
\begin{array}{c}
Ls \\
Ms \\
ss \\
\end{array}
\right]
\end{equation}
"

In [164]:
O = zeros(Char, 3,3)
O |> latexify

L"\begin{equation}
\left[
\begin{array}{ccc}
  &   &   \\
  &   &   \\
  &   &   \\
\end{array}
\right]
\end{equation}
"

In [165]:
U = fill(small, 3,3)
U |> latexify

L"\begin{equation}
\left[
\begin{array}{ccc}
s & s & s \\
s & s & s \\
s & s & s \\
\end{array}
\right]
\end{equation}
"

In [166]:
U * D |> latexify

L"\begin{equation}
\left[
\begin{array}{ccc}
sL & sM & ss \\
sL & sM & ss \\
sL & sM & ss \\
\end{array}
\right]
\end{equation}
"

In [167]:
D * U * D |> latexify

L"\begin{equation}
\left[
\begin{array}{ccc}
LsL & LsM & Lss \\
MsL & MsM & Mss \\
ssL & ssM & sss \\
\end{array}
\right]
\end{equation}
"

In [168]:
print(ans)

\begin{equation}
\left[
\begin{array}{ccc}
LsL & LsM & Lss \\
MsL & MsM & Mss \\
ssL & ssM & sss \\
\end{array}
\right]
\end{equation}


In [169]:
U*D |> latexify

L"\begin{equation}
\left[
\begin{array}{ccc}
sL & sM & ss \\
sL & sM & ss \\
sL & sM & ss \\
\end{array}
\right]
\end{equation}
"

#### 4x4

In [171]:
using LinearAlgebra
D = diagm(0 => [large, medium, small, tiny])

4×4 Array{Char,2}:
 'L'  ' '  ' '  ' '
 ' '  'M'  ' '  ' '
 ' '  ' '  's'  ' '
 ' '  ' '  ' '  't'

In [174]:
U = fill(small, 4,4)
U |> latexify

L"\begin{equation}
\left[
\begin{array}{cccc}
s & s & s & s \\
s & s & s & s \\
s & s & s & s \\
s & s & s & s \\
\end{array}
\right]
\end{equation}
"

In [175]:
D*U*D |> latexify

L"\begin{equation}
\left[
\begin{array}{cccc}
LsL & LsM & Lss & Lst \\
MsL & MsM & Mss & Mst \\
ssL & ssM & sss & sst \\
tsL & tsM & tss & tst \\
\end{array}
\right]
\end{equation}
"

In [179]:
D

4×4 Array{Char,2}:
 'L'  ' '  ' '  ' '
 ' '  'M'  ' '  ' '
 ' '  ' '  's'  ' '
 ' '  ' '  ' '  't'

In [178]:
U*D*U |> latexify

L"\begin{equation}
\left[
\begin{array}{cccc}
sts & sts & sts & sts \\
sts & sts & sts & sts \\
sts & sts & sts & sts \\
sts & sts & sts & sts \\
\end{array}
\right]
\end{equation}
"

## Using Sympy

In [19]:
using SymPy
using LinearAlgebra

In [20]:
X, x, ₓ = @vars X x ₓ

(X, x, ₓ)

In [21]:
D = diagm([X,x,ₓ])

3×3 Array{Sym,2}:
 X  0  0
 0  x  0
 0  0  ₓ

In [22]:
U = fill(x, 3,3)

3×3 Array{Sym,2}:
 x  x  x
 x  x  x
 x  x  x

In [23]:
U*D

3×3 Array{Sym,2}:
 X*x  x^2  x*ₓ
 X*x  x^2  x*ₓ
 X*x  x^2  x*ₓ

In [24]:
⚫, ⬤, ●, 🞄 = @vars ⚫ ⬤ ● 🞄

(⚫, ⬤, ●, 🞄)

In [25]:
D = diagm([⚫, ⬤, ●, 🞄])

4×4 Array{Sym,2}:
 ⚫  0  0  0
 0  ⬤  0  0
 0  0  ●  0
 0  0  0  🞄

In [26]:
Diagonal([1000, 100, 10, 1]) |> latexify

L"\begin{equation}
\left[
\begin{array}{cccc}
1000 & 0 & 0 & 0 \\
0 & 100 & 0 & 0 \\
0 & 0 & 10 & 0 \\
0 & 0 & 0 & 1 \\
\end{array}
\right]
\end{equation}
"

In [27]:
⬛, ■, ◾, ▪ = @vars ⬛ ■ ◾ ▪
L, M, s, t = @vars L M s t

(L, M, s, t)

In [28]:
d = [⬛, ■, ◾, ▪]
d = [L, M, s, t]

4-element Array{Sym,1}:
 L
 M
 s
 t

In [29]:
D = diagm(d)

4×4 Array{Sym,2}:
 L  0  0  0
 0  M  0  0
 0  0  s  0
 0  0  0  t

In [30]:
U = fill(◾, 4,4)
U = fill(s, 4,4)

4×4 Array{Sym,2}:
 s  s  s  s
 s  s  s  s
 s  s  s  s
 s  s  s  s

In [31]:
R = D*U*D

4×4 Array{Sym,2}:
 L^2*s  L*M*s  L*s^2  L*s*t
 L*M*s  M^2*s  M*s^2  M*s*t
 L*s^2  M*s^2    s^3  s^2*t
 L*s*t  M*s*t  s^2*t  s*t^2

In [32]:
A = U*U
A*D

4×4 Array{Sym,2}:
 4*L*s^2  4*M*s^2  4*s^3  4*s^2*t
 4*L*s^2  4*M*s^2  4*s^3  4*s^2*t
 4*L*s^2  4*M*s^2  4*s^3  4*s^2*t
 4*L*s^2  4*M*s^2  4*s^3  4*s^2*t

In [33]:
A = U*D
U*A

4×4 Array{Sym,2}:
 4*L*s^2  4*M*s^2  4*s^3  4*s^2*t
 4*L*s^2  4*M*s^2  4*s^3  4*s^2*t
 4*L*s^2  4*M*s^2  4*s^3  4*s^2*t
 4*L*s^2  4*M*s^2  4*s^3  4*s^2*t

In [34]:
U |> latexify |> print

\begin{equation}
\left[
\begin{array}{cccc}
s & s & s & s \\
s & s & s & s \\
s & s & s & s \\
s & s & s & s \\
\end{array}
\right]
\end{equation}


In [35]:
D |> latexify |> print

\begin{equation}
\left[
\begin{array}{cccc}
L & 0 & 0 & 0 \\
0 & M & 0 & 0 \\
0 & 0 & s & 0 \\
0 & 0 & 0 & t \\
\end{array}
\right]
\end{equation}


In [213]:
D*(U*D) |> latexify |> print

\begin{equation}
\left[
\begin{array}{cccc}
L^2*s & L*M*s & L*s^2 & L*s*t \\
L*M*s & M^2*s & M*s^2 & M*s*t \\
L*s^2 & M*s^2 & s^3 & s^2*t \\
L*s*t & M*s*t & s^2*t & s*t^2 \\
\end{array}
\right]
\end{equation}


In [222]:
U + D |> latexify |> print

\begin{equation}
\left[
\begin{array}{cccc}
L + s & s & s & s \\
s & M + s & s & s \\
s & s & 2*s & s \\
s & s & s & s + t \\
\end{array}
\right]
\end{equation}


In [262]:
X = diagm([1e128, 1e64, 1e0, 1e-64])
# N = rand(4,4)
# N[diagind(N)] .= 0
# X = X+N

4×4 Array{Float64,2}:
 1.0e128  0.0     0.0  0.0    
 0.0      1.0e64  0.0  0.0    
 0.0      0.0     1.0  0.0    
 0.0      0.0     0.0  1.0e-64

In [263]:
F = svd(X)

SVD{Float64,Float64,Array{Float64,2}}
U factor:
4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0
singular values:
4-element Array{Float64,1}:
 1.0e128
 1.0e64 
 1.0    
 1.0e-64
Vt factor:
4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

In [264]:
s = F.S

4-element Array{Float64,1}:
 1.0e128
 1.0e64 
 1.0    
 1.0e-64

In [265]:
using GenericSVD

In [266]:
Xb = big.(X);

In [267]:
Fb = svd(Xb)

┌ Warning: keyword `alg` ignored in generic svd!
└ @ GenericSVD C:\Users\carsten\.julia\packages\GenericSVD\w8oZE\src\GenericSVD.jl:12


SVD{BigFloat,BigFloat,Array{BigFloat,2}}
U factor:
4×4 Array{BigFloat,2}:
 -1.0   0.0   0.0   0.0
  0.0  -1.0   0.0   0.0
  0.0   0.0  -1.0   0.0
  0.0   0.0   0.0  -1.0
singular values:
4-element Array{BigFloat,1}:
 1.000000000000000075174486916518208627471429064352408213482909102357765925242415e+128
 1.0000000000000000213204190094543968723012578712679649467743338496e+64               
 1.0                                                                                  
 9.999999999999999653057388335469287129029766072807834803722132478776394919962261e-65 
Vt factor:
4×4 Array{BigFloat,2}:
 -1.0  -0.0  -0.0  -0.0
 -0.0  -1.0  -0.0  -0.0
 -0.0  -0.0  -1.0  -0.0
 -0.0  -0.0  -0.0  -1.0

In [268]:
sb = Fb.S

4-element Array{BigFloat,1}:
 1.000000000000000075174486916518208627471429064352408213482909102357765925242415e+128
 1.0000000000000000213204190094543968723012578712679649467743338496e+64               
 1.0                                                                                  
 9.999999999999999653057388335469287129029766072807834803722132478776394919962261e-65 

In [269]:
s - sb

4-element Array{BigFloat,1}:
 0.0
 0.0
 0.0
 0.0

In [270]:
using StableDQMC

In [282]:
svd_inv_one_plus(F).S - svd_inv_one_plus(Fb).S

4-element Array{BigFloat,1}:
  1.055257420480776903302833588116958909651870865180872244893734331233485866027102e-146
 -1.33738421569986748693560322601556473903283452878299156314954071924493402990837e-81  
  0.0                                                                                  
  1.000000000000032856963321712779388680454016569740087535451726237621195734616864e-64 

In [297]:
svd_inv_one_plus(F).S

4-element Array{Float64,1}:
 9.999999999999999e-129
 1.0e-64               
 0.5                   
 1.0                   

In [308]:
Fb.U'/Fb.V

4×4 Array{BigFloat,2}:
  1.0  -0.0  -0.0  -0.0
 -0.0   1.0  -0.0  -0.0
 -0.0  -0.0   1.0  -0.0
 -0.0  -0.0  -0.0   1.0

In [320]:
1 / 1.0000001

0.9999999000000099

In [309]:
Diagonal(Fb.S)

4×4 Diagonal{BigFloat,Array{BigFloat,1}}:
 1.0e+128   ⋅        ⋅    ⋅     
  ⋅        1.0e+64   ⋅    ⋅     
  ⋅         ⋅       1.0   ⋅     
  ⋅         ⋅        ⋅   1.0e-64

In [299]:
Fb.U'/Fb.V + Diagonal(Fb.S)

search:

Couldn't find setprecision
Fb.U'/Fb.V + Diagonal(Fb.S)
Perhaps you meant setprecision


No documentation found.

Binding `setprecision Fb.U'/Fb.V + Diagonal(Fb.S)` does not exist.


In [290]:
Ftmp = svd(F.U'/F.V + Diagonal(F.S));

In [294]:
1 ./ Ftmp.S

4-element Array{Float64,1}:
 9.999999999999999e-129
 1.0e-64               
 0.5                   
 1.0                   

In [335]:
x = big"1.0000000000000000000000000000000000000000000000000000000000000000000000001"

1.000000000000000000000000000000000000000000000000000000000000000000000000100007

In [336]:
y = big"1.0000000000000000000000000000000000000000000000000000000000000000000000000"

1.0

In [345]:
reldiff(x,y) = abs(x - y)/abs(x)

reldiff (generic function with 1 method)

In [346]:
reldiff(x,y)

1.00006831867993668761973954571228627033523284220172138438574486184552293070619e-73

In [347]:
reldiff(1/x,1/y)

1.000068318679936687619739545712286270335232842201721384385744861845522930906228e-73

In [36]:
Dp = diagm([L, M, s, s])

4×4 Array{Sym,2}:
 L  0  0  0
 0  M  0  0
 0  0  s  0
 0  0  0  s

In [37]:
Dm = diagm([s, s, s, t])

4×4 Array{Sym,2}:
 s  0  0  0
 0  s  0  0
 0  0  s  0
 0  0  0  t

In [38]:
A = U * inv(Dp)

4×4 Array{Sym,2}:
 s/L  s/M  1  1
 s/L  s/M  1  1
 s/L  s/M  1  1
 s/L  s/M  1  1

In [39]:
B = U * Dm

4×4 Array{Sym,2}:
 s^2  s^2  s^2  s*t
 s^2  s^2  s^2  s*t
 s^2  s^2  s^2  s*t
 s^2  s^2  s^2  s*t

In [40]:
A + B

4×4 Array{Sym,2}:
 s^2 + s/L  s^2 + s/M  s^2 + 1  s*t + 1
 s^2 + s/L  s^2 + s/M  s^2 + 1  s*t + 1
 s^2 + s/L  s^2 + s/M  s^2 + 1  s*t + 1
 s^2 + s/L  s^2 + s/M  s^2 + 1  s*t + 1

In [42]:
inv(Dp) * U |> latexify |> print

\begin{equation}
\left[
\begin{array}{cccc}
s/L & s/L & s/L & s/L \\
s/M & s/M & s/M & s/M \\
1 & 1 & 1 & 1 \\
1 & 1 & 1 & 1 \\
\end{array}
\right]
\end{equation}


## Using custom types

In [1]:
] activate .

Activating environment at `C:\Users\carsten\.julia\dev\StableDQMC.jl\notebooks\scales_visualizations\Project.toml`


In [92]:
@enum Scale null=1 tiny=2 small=3 medium=4 large=5
const unit=small
# const scale_symbols = [' ', '▪', '◾', '■', '⬛'];
const scale_symbols = [' ', 't', 's', 'M', 'L'];
# const scale_symbols = [' ', 'ₓ', 'u', 'x', 'X'];

symbol(s::Scale) = scale_symbols[Int(s)]
Base.isascii(::Scale) = false
Base.isoverlong(::Scale) = false
Base.ismalformed(::Scale) = false
Base.isprint(::Scale) = true

# printing
Base.show(io::IO, s::Scale) = print(io, symbol(s))
Base.show(io::IO, ::MIME"text/plain", s::Scale) = show(io,s)
Base.print(io::IO, s::Scale) = show(io, s)

# math
Base.zero(::Type{Scale}) = null
Base.iszero(s::Scale) = s === null

In [93]:
scales = null, tiny, small, medium, large

( , t, s, M, L)

In [94]:
using Statistics

struct ScaleString <: AbstractString
    scales::Vector{Scale}
end

# constructors
ScaleString(s::Scale) = ScaleString([s])

import Lazy: @forward
@forward ScaleString.scales (Base.getindex, Base.length)

# conversion
Base.convert(::Type{ScaleString}, s::Scale) = ScaleString(s)
Base.promote_rule(::Type{Scale}, ::Type{ScaleString}) = ScaleString

Base.iterate(s::ScaleString) = iterate(s.scales)
Base.iterate(s::ScaleString, state::Integer) = iterate(s.scales, state)

# Base.:+(x::ScaleString, y::ScaleString) = ScaleString(vcat(x.scales, null, null, y.scales))
Base.:*(x::ScaleString, y::ScaleString) = ScaleString(vcat(x.scales, y.scales))
Base.zero(::Type{ScaleString}) = ScaleString(zero(Scale))
Base.zero(::ScaleString) = zero(ScaleString)
function Base.:+(x::ScaleString, y::ScaleString)
    if null in x.scales
        if null in y.scales
            # both contain a null
            return ScaleString([null])
        else
            # only x contains a null
            return y
        end
    elseif null in y.scales
        # only y contains a null
        return x
    else
       return sum(Int.(x.scales)) < sum(Int.(y.scales)) ? y : x #mean(x) < mean(y) ? y : x 
    end
end
Base.:*(x::ScaleString, y::Scale) = iszero(y) ? ScaleString([null]) : ScaleString(vcat(x.scales, y))
Base.:*(x::Scale, y::ScaleString) = iszero(x) ? ScaleString([null]) : ScaleString(vcat(x, y.scales))

# Scale math extension
Base.:+(x::Scale, y::Scale) = x > y ? x : y
Base.:/(s::Scale, i::Int64) = /(Int(s), i)
function Base.:*(x::Scale, y::Scale)
#     if iszero(x)
#         return ScaleString([y])
#     elseif iszero(y)
#         return ScaleString([x])
#     else
        return ScaleString([x,y])
#     end
end

In [95]:
tiny * null

"t "

In [96]:
A = ScaleString([tiny, small, small])
B = ScaleString([null, large, small])

" Ls"

In [97]:
using Latexify

Latexify.latexraw(s::Scale) = symbol(s)
Latexify.latexraw(s::ScaleString) = join(s.scales)

In [98]:
O = zeros(Scale, 4,4)

4×4 Array{Scale,2}:
           
           
           
           

In [99]:
U = fill(unit, 4,4)

4×4 Array{Scale,2}:
 s  s  s  s
 s  s  s  s
 s  s  s  s
 s  s  s  s

In [100]:
U |> latexify

L"\begin{equation}
\left[
\begin{array}{cccc}
s & s & s & s \\
s & s & s & s \\
s & s & s & s \\
s & s & s & s \\
\end{array}
\right]
\end{equation}
"

In [101]:
U * U |> latexify

L"\begin{equation}
\left[
\begin{array}{cccc}
ss & ss & ss & ss \\
ss & ss & ss & ss \\
ss & ss & ss & ss \\
ss & ss & ss & ss \\
\end{array}
\right]
\end{equation}
"

In [102]:
U * O

4×4 Array{ScaleString,2}:
 " "  " "  " "  " "
 " "  " "  " "  " "
 " "  " "  " "  " "
 " "  " "  " "  " "

In [103]:
using LinearAlgebra
D = diagm([large, medium, small, tiny])

4×4 Array{Scale,2}:
 L         
    M      
       s   
          t

In [104]:
D |> latexify

L"\begin{equation}
\left[
\begin{array}{cccc}
L &   &   &   \\
  & M &   &   \\
  &   & s &   \\
  &   &   & t \\
\end{array}
\right]
\end{equation}
"

In [105]:
U * D |> latexify

L"\begin{equation}
\left[
\begin{array}{cccc}
sL & sM & ss & st \\
sL & sM & ss & st \\
sL & sM & ss & st \\
sL & sM & ss & st \\
\end{array}
\right]
\end{equation}
"

In [106]:
D * U * D |> latexify

L"\begin{equation}
\left[
\begin{array}{cccc}
LsL & LsM & Lss & Lst \\
MsL & MsM & Mss & Mst \\
ssL & ssM & sss & sst \\
tsL & tsM & tss & tst \\
\end{array}
\right]
\end{equation}
"

In [107]:
D * [small, small, small, small] |> latexify

L"\begin{equation}
\left[
\begin{array}{c}
Ls \\
Ms \\
ss \\
ts \\
\end{array}
\right]
\end{equation}
"

In [108]:
D * [large, medium, small, tiny] |> latexify

L"\begin{equation}
\left[
\begin{array}{c}
LL \\
MM \\
ss \\
tt \\
\end{array}
\right]
\end{equation}
"

In [109]:
R = D * U * D
R[1] == ScaleString([large,unit,large])

true